package comm;

public enum Operation {
    LOGIN,
    LOGOUT,

    UCITAJ_VRSTE_TRENINGA,

    KREIRAJ_KORISNIK,
    SACUVAJ_NOVOG_KORISNIKA,
    PRETRAZI_KORISNIKE,
    NADJI_KORISNIKA,
    IZMENI_KORISNIKA,
    OBRISI_KORISNIKA,
    
    DODAJ_LICENCU,
    GET_LICENCE,

    UCITAJ_TRENINZI,
 
    PRIZNANICA_KREIRAJ,
    PRIZNANICA_PRETRAZI,
    PRIZNANICA_IZMENI,
    PRIZNANICA_GET_ONE,
    
    
//    TRENING_KREIRAJ,
//    TRENING_PRETRAZI,
//    TRENING_IZMENI,
//    TRENING_OBRISI,
//
//    TRENER_GET_ALL,
//
//    TRENER_LICENCA_DODAJ,
//    TRENER_LICENCA_GET_ALL,
}